---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBKagqzqxQ8QTw9Hd9gbLMxLyKfHkPYk+hJg/h22nbPPvtUT3j7Wk38NMKPhaXmIjhcZplgSkXIor/qFYo0RFvCMZzx4I+r7nYuZpJyXjkCYpCDb/cwWgkjqNLJnRw+smuL70fbh6xElPRwHEROOx9BU5KYCxG4hDNEGdoY9blVFtN4tehMXC+/v0WBloNbF/NNJukssUUr/29PiN8SLf8Nic+9gDQ63G/bd8/aTEKHxXMIkWsK2LY5h2OwD6Gaspt+diOj6VcHl+vT+CVyXAmh5RRqe7nNpWUmax/X9+fXmDqJmyRkXMCoj39/0U2Laac61D3Hy++6T3TSjS6ZZxVVM6ndUwKqz2MrqXp45712Li96iFPhIlVFjuT8ErO2wjjTGL6mkOOX8awWt5UjKrUJMByyV6x3W2tqc+8AzndhbWG74MdHu9HQUb/+tMp+M0tV5nd71l3fv0l8VtqnWKxDxbHRyhzerZ/qDQbiaKekbxjtQBdlOdMVqAC4n6ZfYPwQ/8gQyjnXc5yfXlV+0b/wwxHvOCNcAf3xmK3c4XZTOJfDtpRpgmALn/NClOWtTkBKCVYt/k//MEciUaYsRE2v+99P+5qjkPhsQXXNq9UIDPWeB+DSv999j4IvaGnvY+oYaA8gYf5ltIcEGD2KFAomnEKAK6kpxSbSVjhZ27vhZT2Dsc5v5NfzMQ6Vdtn0umyw3Z68GRQyQBur2G5Izg==
    admin-user: AgCxArtFoLLxwboLIhnCPAmCNQSp4/QBrse+crFZALiTE/Mkzwt/gikKGJqYmMrGkyFnTKjdmnZHI2HyNYN3tCtoOfrxULBgWiwnZ4egxbGo5ujGPA028kKQ290MpnAnTgABUma+8FfxVqo5foftPdqVUBb71STBPhicHoAFraVv2YnkPH0cFSnC5qdFMpJYeN4vTdL5oeh2+88Y3qt56sSsSSE4bjw0XkKRtim4HOwiDz1NOc5GGPRHlekY2s3LjPOzWNsmQ9lOdDQfX3f809FJKOPLxlg6V3eihDMRx7o++HOeb2a9d1gxiTh/it+NbKDP8xzE7qeNS4dW6QtSltJB6qZnAjVWZjQoafBoqjY8eQxMgQtoAf6oYxma2ekAQbu8pENAoA/5Y5SvswviPlmoW03hC1sQyp7cBfqjisjSM55BXUZqjHEjwHhYq0nYywY4gVmVoLwf7cWSmTgDqfKn0q3XM1bjEf2Abgn4SuBnGSZSqydMjMVUeWfjf/1jrxk7163OsckBECUdhB6smw+AE5bpMAnAH34jxDIJdBgrDDkVn/J79CAqH/UZyLKAeBa5xm70v6Br7yOndW/Co5ajMFj3RPgcTxj2e4kVkm7FOOeY6RmZc3LwUYqh8PROXNv4Fw+WRdVr9dQ32Lg7i1SMwzvgBucqQvu4jyoXDfnXWlipcoFOja8HUkCEYOqLxY8TQeVWtA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
