---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-user-credentials
  namespace: samba
spec:
  encryptedData:
    user-name: AgCk69t0CHai8rxhfNQQdwvC9D3fMtFdZTMuQmow5QEdiatYlHVWE8XTQJb8qD4z/eHevAEZUmhAhzWp660Lch3EJbJz9+mUb0bSnTQzRhyFE2rZX7n2AjKNFsYjTfThmIE/u9H0TMRufdgebF6FXixetqM7rnlV61kKFQKwcjQ7UsOflCxnUzxfQJlDTScrY3RL7YsLr+os0aKHTEBe+9zqHxwz/7CoZ5K01/U/XfhMfNQZCxLMMqGdAzDK3MdPqETwkJ2rQ3os4yvD9fDdY2ktDi5Lekn8NONRgUB2zg/PbszbE94qvsi3tI/2qxW+oR5WzSIbGjABGvZlQgR8OHpRE2ePkGrGBQ8/MoAtUmBUoMSYR8sQBIXBMDM751YHP/fKAsrEbFyAX9Eg9o7vQEqoR4BT/6YYFH/Jn7Xk3EYNb7ZlUnHGuCsYGl3BaKa7+fEK4y9sevkMpQsngcszpAFIhnv80Nnk7AAxGJItBWFgthAhidgWxS7HjQnLY5Fe55TolPq4M4N3tZL1RdRztISR79ZhyF65Z1UTq1i7RBY1ErVV/yAllnmenTaOyM2OtIs/3zSELrD98J5e3aWtJVmQvaa6y9vwWXqOecyexG8CqzRH6AlPAuvhIqdKEGnuo1uzY7pdAaoTIpdBaFj+/xfBoh6JpWBANRiLKM4fSOU8s4xdjG7Iyi2/asGTBEArMKs9HDeJqBA=
    user-password: AgCv8+oRi6IUXa1C/arclqscxpZEkqOZHOBEoFF0wdi/ALzJ/pvEOPPi859OoNYfCMIZKBSILXBNsJGyphAxmotiM+X/VAxarlgvlqCKV43e4ea8B+xJUYq0JGGsbkvvOvwARWTJnsIuZac5+5PiQ54QQc4VQTAEFxi1S5R8EJQhLo9mG8KlwIyZh85GuIvMKd+r4lExsRQONlh6Hk6P/2/l5gtMRT3fh0ZJhaK5bpxE5kBCplM65ekO+ert9Thfc/zR6U7ocFg91yboOCyZOUl4PgAKgfAh3ARYcxbLSbeemR68VmHnA+ElpBp+LeFf7KhARaL12fFuZKShLaiu6BHGqIyG6x72tVkrhXRidK4RM6c9yjLenlvH+Aj7AOOpwg85XQHnK5AfwuCEIV+HnVBx0W8zBo32kBUmhj+9KsuRx3fGra83IoNIaMqCeSH4qTPpu/IWlSgbdnkYk5Ttg7z8SVjyHxay+RtKyo8qwz+H+hFZmKfRPPneMUjJxyQ7AsbnziuyoPGg+YmCNfZHOu0oMqmPlusckMaZjy5Lg1RZ81lkzGrtU+RjmWlVS6Cv7N9m9oCdh8xHowu0Dy+4jhYWX813SQ+OkR35UBEaA5SZ7HiIirhizMtwf+Kig27k+RXn5aBpf+nM2UdfW87a29Pp/zENc39+RAicWjbWb7FMFb203xFLmYFQ7ZKCEkOo8ChRncI7Brjuoa6w67PSVHzUSw==
  template:
    metadata:
      name: samba-user-credentials
      namespace: samba
    type: Opaque
