---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-secret
  namespace: immich
spec:
  encryptedData:
    password: AgBE9z6z2SPRSYvEzSOGvRPL0y3pkuGnjiL8NHDQxN4lAVm+aqb7oIlqdrNTaRNYi+D5ewRBVAQbkIIxBJcWMQh7gjdYum/gr8Fbn8wCxY8FNcklG8oG3Y5RD/C3caNFVzgKQH3N2qSiZn+ElBL1xbNPhR9Rn63/KGyN8uJUhi1OS6yiaatCJFmE8q135yYewBobd7/gvOayJoUb2oI/zsmc/GUkuVa45LCKawoI7UuirUOVus+GIV4ZfZJMLRxmHBLVRIUvo55TDH5g7QCivlf7QQPCK6a5K3YCPXTkzgN87aJD5qafjh9sNNA5r7K2f/rF9iFsz+mYw892uyFjznXis8p5r4PpYoQX0uSrEi1IK2PXZPsSX5S2byLPCpeFrIO92ym4HNJzUYuAm2uzQPOs3KsbKTYvPRfMkGIUXPDPwmfRcN3BJvh/F61l99v2vjwUDvcbtPEAALPvf9oOJFmsiGaBKktHqLwLEKFttplLd/oUXZ7e7bFVVQkTG26BPKObQTaEfhgaZLk02uWSiIG7TzPt/QqGg31di+vp7z6Be3tBiSrJQ49IMfljGIWwoIXOPrVGX5cEFTChsCCV6hC2YhYhzuZ+QMBNx8rKGbdIWDNohhMQdAXWNWaHTd5LYv7sTa/sQRQ/gsyWtp38iH9yO+8KHpT6AqDuwlngBt/k8L4JhgH27uf7lpah9Q5qSO9T7Ls2R1aoR47KIlChTXM2BAed/dKwwOsNlYZ9yQ9XVgJ4dfY=
    username: AgC5wMxeJV9c/zT9iiGl5o6UtJftBs8OD1ZYPgRQiZbvElKj0xNN0fOPfVR4bSaorgW6+AorkpcsPTKmRxQLLOQ+sTRuGJYKXgoQfz5YSZmtL3JuE0R03pzNW/Xyt44qy1G05dZLZNwDfb0AGiMpOTn0KLtk2XiytRriBXstAf4NWiBkmHg7u5KdR78UNA9ylpl9eUoxwSvP9vqLD1XK8uT3ytJcKlzZGJwk4N+ol2LI/Kfo1nL/gJenjaJqlFurH0ohH+SXgWWEDAcPwNuZaIZST7Dj5qFmVdqCxi6+MA5fajFe888xOBlEKBf0FDImq2oof46HmQvy+BW6jxuYjMm8ofQSP17PrYhXwh7Y/PP1cZWrYGkV8NPZb2hmNf+U3uMkEzbafIILUVUlUFkbsP2vWedukrtPNl8KwLMeoDlgrvNXDzOciRw9d9MecCIqVFyiJS4IWMvN1dvD2dt2YlYcfOebdiDmFEKwB1sPpOhcGO/pRCSF+GS7LMtl9FjBitgO4o4peD1T17ty8izNGEWh0k694jdRAnb0yN48u3dMlyJVblUaaZtWMEIM8qkgQjAeZWlbF84iAyjMCIlafDshdDxdAL+XJPx1BE52XfeJ5ePj2LjWfnZYsdRtSNbyFPfQEibV+5qoJRt9euPzMszAHrE39vBCnTpBmGLRGo/4okrawbVuZfGysNaQR15u1w5VZ8+4yn+LefWo
  template:
    metadata:
      name: immich-db-secret
      namespace: immich
    type: Opaque
