---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAVf0KbcpTIkZYuE5rUpoyqutReyPKSJdgphGmTIr9R56iKot/zUJnVc4q11RvenD0uyCGACD/hz2e0M29jJKvJfI3X+pG2B9YK43fhfuQWJhKyXZXMyYmf03L223le4IaIx+OCcDOj6O/DbylNcCwlq/lrjvZYKukcsb9631dg7ghGdLx3LQF+924glVh2reKMhp8F0zKe71HAdvx3PM9Na9wq+i4AheKYy52KteYIKvvfQOsAtu6kdvHbnzsXFjGtsQnbHfPCl6eqvvah7zVfJvxH3WJt0QiRNcBjZCiKDBkoGpGDgtEL/iSZNmVSZCeLFFeMm5TU63v1QakiqYLeU998g4Mk8xtlSTtxlwmGOTz7CqU1jZ7sROAVc/GVHjEcBBZeDleqwFVwTD+l1fGtpiQXN4u/oHx31kT8S4uj41BT5JcLvM+pVv2eynWbFBaESdEy/A2/uHG3lqRAJ5+chN2kQVM4EgirKUofKBZXfLtkgqlJItsPEnnvQ5XL21WqHQawQtVzOeNWcK4TvvYyDdz7q0r42As9dhqZzrBuTCZDhkHmyMCC9FR4mrdyWrWKtdEKJGho5mcl4X41SjURZeAx3IDFG3Mi6B27BoQ0GSPM7pPoQkBUI0g58SDdWY4auYkxhdp3fXd3pasvc4xWDS3oLGNAIWTelEhk0/fka2xEc9wjAJvXldkKGR4jPOQB4Ba5/dZXnwwYKoErVMlLPF1oMnWW8GYcwW6O2xPKx+GLLT8E1uuk
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
