apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.20.3
      helm:
        valueFiles:
          - $values/argocd/configurations/infrastructure/cert-manager/values.yaml
          
    - repoURL: 'git@github.com:andresdelgadillo/adn-homelab-gitops.git'
      targetRevision: main
      ref: values

    - repoURL: 'https://github.com/andresdelgadillo/adn-homelab-gitops.git'
      targetRevision: main
      path: argocd/configurations/infrastructure/cert-manager
      directory:
        exclude: '{values.yaml,*.md}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true