apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  project: infrastructure
  sources:
    # Source 1: The official CNPG Helm Chart
    - repoURL: 'https://cloudnative-pg.github.io/charts'
      chart: cloudnative-pg
      targetRevision: 0.27.1
      helm:
        releaseName: cnpg
        valueFiles:
          - $values/argocd/configurations/infrastructure/cnpg-operator/values.yaml

    # Source 2: Your Git repository for values
    - repoURL: 'https://github.com/andresdelgadillo/adn-homelab-gitops.git'
      targetRevision: main
      ref: values

    # Source 3: Raw manifests folder
    - repoURL: 'https://github.com/andresdelgadillo/adn-homelab-gitops.git'
      targetRevision: main
      path: argocd/configurations/infrastructure/cnpg-operator
      directory:
        exclude: '{values.yaml,*.md}'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system 
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true