apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-andres
  namespace: samba
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 274Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media
  namespace: samba
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 572Gi